cancer/cancer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^$', 'cancer.views.login_view'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^dashboard/',include('dashboard.urls')),

	#login logout
	url(r'^accounts/login/$',  'cancer.views.login_view'),
    url(r'^accounts/logout/$', 'cancer.views.logout_view'),
    url(r'^accounts/loggedin/$', 'cancer.views.loggedin'),
   	url(r'^accounts/register/$', 'cancer.views.register_user'),
    url(r'^accounts/register_success/$', 'cancer.views.register_success'),
	url(r'^accounts/logout_success/$', 'cancer.views.logout_success'),

    url(r'session_security/', include('session_security.urls')),

	url(r'^help/$',  'cancer.views.help'),	
]

cancer/dashboard/urls.py
from django.conf.urls import url
from . import views


try:
    from django.conf.urls import patterns, url, include
except:
    from django.conf.urls.defaults import patterns, url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    	url(r'^$', views.index, name='index'),
    	url(r'^db/(?P<db_name>\w+)/$', views.db_search, name='db_search'),
    	url(r'^db/(?P<db_name>\w+)/download$', views.db_download, name='db_download'),
    	url(r'^search/$', views.general_search, name='general_search'),
    	url(r'^get/(?P<DB_ID>\w+)/$', views.detail, name='detail'),
]

cancer/dashboard/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

import datetime
from django.utils import timezone
from django.utils.encoding import smart_unicode
from django.contrib.auth.models import User
import uuid
import string

PATIENT_SEX_CHOICES = (
	(1, "男"),
	(2, "女")
)


#关系（1 父母，2 配偶，3 子女，4 其它）
PATIENT_RELATIVE_CHOICES = (
	(1, "父母"),
	(2, "配偶"),
	(3, "子女"),
	(4, "其他"),
)

#在随访中（1 是，2 不是）
PATIENT_IN_CONTACT_CHOICES = (
	(1, "是"),
	(2, "不是")
	)
					
#住院科室 （1 骨科，2 放疗科，3 肿瘤科，4 血液科）
CANCER_DEPARTMENT_CHOICES = (
	(1, "骨科"),
	(2, "放疗科"),
	(3, "肿瘤科"),
	(4, "血液科"),
)

#诊断依据（1 手术病理，2 穿刺病理，3 其它）
CANCER_DIAGNOSIS_BASIS_CHOICES = (
	(1, "手术病理"),
	(2, "穿刺病理"),
	(3, "其它"),
)

#肿瘤性质（1 原发，2 转移，3 不确定）
CANCER_PROPERTY_CHOICES = (
	(1, "原发"),
	(2, "转移"),
	(3, "不确定"),
)

#肿瘤分类（1 良性，2 恶性）
CANCER_TYPE_CHOICES = (
	(1, "良性"),
	(2, "恶性")
	)

#肿瘤复发（1 首发，2 复发）
CANCER_RECURRENCE_CHOICES = (
	(1, "首发"),
	(2, "复发")
	)

#脊柱病灶数目（1 单发，2 多发）
CANCER_FOCUS_CHOICES = (
	(1, "单发"),
	(2, "多发")
	)

#肿瘤部位（1 上颈椎，2 下颈椎，3 颈胸段，4 上胸椎，5 下胸椎，6 腰椎，7 骶尾椎）
CANCER_LOCATION_CHOICES = (
	(1, "上颈椎"),
	(2, "下颈椎"),
	(3, "颈胸段"),
	(4, "上胸椎"),
	(5, "下胸椎"),
	(6, "腰椎"),
	(7, "骶尾椎"),
)

#脊柱外骨累及（1 有，2 无）
CANCER_INFECTION_SPINAL_CHOICES = (
	(1, "有"),
	(2, "无")
	)

#原发灶外重要脏器累及（如肺、肝、脑）（1 有，2 无）
CANCER_INFECTION_ORGAN_CHOICES = (
	(1, "有"),
	(2, "无")
	)

#重要脏器累及可控制（1 是，2 否）
CANCER_INFECTION_ORGAN_CONTROLLABLE_CHOICES= (
	(1, "是"),
	(2, "否")
	)


#夜间痛（1 有，2 无）
SYMPTOM_NIGHT_PAIN_CHOICES = (
	(1, "有"),
	(2, "无"),
)

#疼痛需卧床缓解（1 是，2 否）
SYMPTOM_STAY_IN_BED_CHOICES = (
	(1, "有"),
	(2, "无"),
)

#根性疼痛（1 有，2 无）
SYMPTOM_ROOT_PAIN_CHOICES = (
	(1, "有"),
	(2, "无"),
)
#肢体麻木无力（1 有，2 无）
SYMPTOM_NUMB_CHOICES = (
	(1, "有"),
	(2, "无"),
)

#体表包块（1 有，2 无）
SYMPTOM_ENCLOSED_MASS_CHOICES = (
	(1, "有"),
	(2, "无"),
)

#小便异常（1 有，2 无）
SYMPTOM_ABNORMAL_URINE_CHOICES = (
	(1, "有"),
	(2, "无"),
)
#最重病变水平以远肌力（1 正常，2 减弱
SYMPTOM_MUSCLE_CHOICES = (
	(1, "正常"),
	(2, "减弱"),
)
#最重病变水平以远感觉（1 正常，2 减弱
SYMPTOM_FEEL_CHOICES = (
	(1, "正常"),
	(2, "减弱"),
)


#手术入路（1 后路 2 前路 3 侧前方入路 4 前后联合 5颌下入路 6经口入路 7劈下颌骨入路）
TREATMENT_APPROACH_CHOICES = (
	(1, "后路"),
	(2, "前路"),
	(3, "侧前方入路"),
	(4, "前后联合"),
	(5, "颌下入路"),
	(6, "经口入路"),
	(7, "劈下颌骨入路"),
)

#手术部位（1上颈椎 2下颈椎 3颈胸段 4上胸椎 5下胸椎 6腰椎 7骶骨）
TREATMENT_LOCATION_CHOICES = (
	(1, "上颈椎"),
	(2, "下颈椎"),
	(3, "颈胸段"),
	(4, "上胸椎"),
	(5, "下胸椎"),
	(6, "腰椎"),
	(7, "骶骨"),
)

#手术方式（1姑息性减压 2囊内刮除 3囊外经瘤切除 4边缘性整块切除 5广泛性整块切除）
TREATMENT_METHOD_CHOICES = (
	(1, "姑息性减压"),
	(2, "囊内刮除"),
	(3, "囊外经瘤切除"),
	(4, "边缘性整块切除"),
	(5, "广泛性整块切除"),
)


#术后并发症（1伤口感染 2咽后壁感染或不愈合 3肺炎 4泌尿系感染 5神经损害表现）
TREATMENT_POST_COMPLICATION_CHOICES = (
	(1, "伤口感染"),
	(2, "咽后壁感染或不愈合"),
	(3, "肺炎"),
	(4, "泌尿系感染"),
	(5, "神经损害表现"),
)

#部位（1 椎体一侧 2 整个椎体 3椎体一侧+附件 4整个椎体+附件）
TREATMENT_BONE_CEMENT_LOCATION_CHOICES = (
	(1, "椎体一侧"),
	(2, "整个椎体"),
	(3, "椎体一侧+附件"),
	(4, "整个椎体+附件"),
)

#支具类型（1 Halo架，2 枕颈胸支具，3 颈椎围领（颈托），4 胸腰椎支具）
TREATMENT_SUPPORT_THERAPY_TYPE_CHOICES = (
	(1, "Halo架"),
	(2, "枕颈胸支具"),
	(3, "颈椎围领（颈托）"),
	(4, "胸腰椎支具"),
)
#药物（1 二磷酸盐，2 狄诺塞麦，3干扰素，靶向药物） other_treatment_drug
TREATMENT_OTHER_TREATMENT_DRUG_CHOICES = (
	(1, "二磷酸盐"),
	(2, "狄诺塞麦"),
	(3, "干扰素"),
	(4, "靶向药物"),
)

#项目名称（1 手术病理， 2 穿刺病理， 3 PET-CT， 4 病变MR， 5 病变CT， 6 病变X线片 7 骨扫描）
TEST_PROJECT_NAME_CHOICES = (
	(1, "手术病理"),
	(2, "穿刺病理"),
	(3, "PET-CT"),
	(4, "病变MR"),
	(5, "病变CT"),
	(6, "病变X线片"),
	(7, "骨扫描"),
)

################################################################################

class Patient(models.Model):
	DB_ID = models.CharField(max_length=200,blank=True) #, unique=True) TODO
	name = models.CharField(max_length=200,blank=True, null=True)
	EMR_id = models.CharField(max_length=200,blank=True,null=True)
	sex = models.CharField(max_length=200,blank=True, null=True) #models.IntegerField(choices=PATIENT_SEX_CHOICES, null=True,blank=True,)  TODO
	DOB = models.CharField(max_length=200,blank=True,null=True) #models.DateField(blank=True,null=True) TODO
	social_id = models.CharField(max_length=200,blank=True,null=True)
	location = models.CharField(max_length=200,blank=True,null=True)
	phone = models.CharField(max_length=200,blank=True,null=True)
	DOD = models.CharField(max_length=200,blank=True, null=True) #models.DateField(blank=True,null=True) TODO

	#INCOMPLETE FIELDS
	relative = models.IntegerField(choices=PATIENT_RELATIVE_CHOICES, null=True,blank=True,)  #关系（1 父母，2 配偶，3 子女，4 其它）
	relative_phone = models.CharField(max_length=200,blank=True,null=True)
	relative_email  = models.EmailField(max_length=200,blank=True,null=True)
	relative_wechat = models.CharField(max_length=200,blank=True,null=True)
	relative_in_contact = models.IntegerField(choices = PATIENT_IN_CONTACT_CHOICES,null=True,blank=True,)

	#DEFAULT FIELDS
	tagged = models.NullBooleanField(blank=True,null=True)
	comment =  models.CharField(max_length=200,blank=True,null=True)
	created_by = models.ForeignKey(User,blank=True,null=True,related_name='patient_created')
	created_date = models.DateTimeField("Created Date",default=datetime.datetime.now,blank=True)
	updated_by = models.ManyToManyField(User,blank=True,related_name='patient_updated')
	updated_date = models.DateTimeField("Updated date",auto_now_add=False, auto_now=True,blank=True,null=True)
	download_by = models.ManyToManyField(User,blank=True,related_name='patient_download')
	download_date = models.DateTimeField("Download Date",null=True,blank=True)

	def __unicode__(self):
		return smart_unicode('-'.join([self.DB_ID,str(self.id)]))

	@property	
	def get_absolute_url(self):
		return "/dashboard/get/%s/" % self.DB_ID

'''
	def natural_key(self):
			return (self.name,self.db_id)

	def get_all_samples(self):
		return self.sample_set.all()

	@property
	def get_sorted_sample_set(self):
				return self.sample_set.order_by('created_date')
	@property
	def get_standard_created_date(self):
		#return "%s-%s-%s"%(self.created_date.year, self.created_date.month, self.created_date.day )
		return datetime.datetime(self.created_date.year, self.created_date.month, self.created_date.day,self.created_date.hour,self.created_date.minute,self.created_date.second)
	@property
	def get_taged_project_name(self):
		return u"<span class=\'label label-info\' style=\'font-size:85%%;font-weight:500;background-color:#9999FF;\'><a href=\'%s\'><font color='white'>%s</font></a></span>" % ('/virtual/search/?p='+self.project_name.replace('\s+','%20'), self.project_name)

	@property
	def get_taged_investigator_name(self):
		tags = []
		for i in self.investigator.all():
			tags.append("<span class=\'label label-info\' style=\'font-size:85%%;font-weight:500;background-color:#66C285;\'><a href=\'%s\'><font color='white'>%s</font></a></span>" % ('/virtual/search/?u='+'%20'.join([i.FirstName, i.LastName]), ' '.join([i.FirstName, i.LastName])))
		
		return ', '.join(tags)

	@property
	def get_comma_separated_investigator_name(self):
				tags = []
				for i in self.investigator.all():
						tags.append(' '.join([i.FirstName, i.LastName]))

				return ', '.join(tags)
	
	@property
		def get_taged_created_by_name(self):
				if self.created_by:
			tags="<span class=\'label label-info\' style=\'font-size:85%%;font-weight:500;background-color:#66C285;\'><a href=\'%s\'><font color='white'>%s</font></a></span>" % ('/virtual/search/?u='+'%20'.join([self.created_by.FirstName, self.created_by.LastName]), ' '.join([self.created_by.FirstName, self.created_by.LastName]))

					return tags
		else:
			return ''


	@property	
	def get_absolute_url(self):
		return "/virtual/get/%s/" % self.experiment_id

'''

class Cancer(models.Model):
	patient = models.CharField(max_length=200,blank=True) # models.ForeignKey(Patient, null=True,related_name='cancers') TODO
	DB_ID = models.CharField(max_length=200,blank=True) #, unique=True) TODO
	name = models.CharField(max_length=200,blank=True, null=True)
	EMR_id = models.CharField(max_length=200,blank=True,null=True)
	
	admission_date = models.CharField(max_length=200,blank=True, null=True) #models.DateField(blank=True,null=True) TODO
	discharge_date = models.CharField(max_length=200,blank=True, null=True) #models.DateField(blank=True,null=True) TODO
	department = models.IntegerField(choices=CANCER_DEPARTMENT_CHOICES, null=True,blank=True,)
	pre_diagnosis = models.CharField(max_length=200,blank=True,null=True)
	diagnosis = models.CharField(max_length=200,blank=True,null=True)
	diagnosis_basis = models.IntegerField(choices=CANCER_DIAGNOSIS_BASIS_CHOICES, null=True,blank=True,)
	cancer_property = models.IntegerField(choices=CANCER_PROPERTY_CHOICES, null=True,blank=True,)
	cancer_type = models.IntegerField(choices=CANCER_TYPE_CHOICES, null=True,blank=True,)
	recurrence = models.IntegerField(choices=CANCER_RECURRENCE_CHOICES, null=True,blank=True,)
	focus = models.IntegerField(choices=CANCER_FOCUS_CHOICES, null=True,blank=True,)
	location = models.IntegerField(choices=CANCER_LOCATION_CHOICES, null=True,blank=True,)
	infection_spinal = models.IntegerField(choices=CANCER_INFECTION_SPINAL_CHOICES, null=True,blank=True,)
	infection_organ = models.IntegerField(choices=CANCER_INFECTION_ORGAN_CHOICES, null=True,blank=True,)
	infection_organ_controllable = models.IntegerField(choices=CANCER_INFECTION_ORGAN_CONTROLLABLE_CHOICES, null=True,blank=True,)

	#DEFAULT FIELDS
	tagged = models.NullBooleanField(blank=True,null=True)
	comment =  models.CharField(max_length=200,blank=True,null=True)
	created_by = models.ForeignKey(User,blank=True,null=True,related_name='cancer_created')
	created_date = models.DateTimeField("Created Date",default=datetime.datetime.now,blank=True)
	updated_by = models.ManyToManyField(User,blank=True,related_name='cancer_updated')
	updated_date = models.DateTimeField("Updated date",auto_now_add=False, auto_now=True,blank=True,null=True)
	download_by = models.ManyToManyField(User,blank=True,related_name='cancer_download')
	download_date = models.DateTimeField("Download Date",null=True,blank=True)

	def __unicode__(self):
		return smart_unicode('-'.join([self.DB_ID,str(self.id)]))
	
	@property	
	def get_absolute_url(self):

cancer/dashboard/templates/consoleView/general_search.html
<!DOCTYPE html>
{% extends "base.html" %}

{% load staticfiles %}



{%block content%}
    
        <ul class="breadcrumb">
          <li><a href="/">主页</a></li>
          <li><a href="/dashboard/">控制台</a></li>
          <li class="active">搜索</li>
        </ul>
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            数据库
          </h1>
        </section>
        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

              <div class="box">
                <div class="box-header">
                </div><!-- /.box-header -->
                <div class="box-body">
        
    <table class="table table-bordered table-striped" id="recent" class="display" cellspacing="0" width="100%" >
        <thead>
            <tr>
                <th colspan="6">病人基本信息</th> 
                <!--
                <th colspan="3">肿瘤基本信息</th>
                <th colspan="4">症状与体征</th>
                <th colspan="3">其他</th>
                -->
            </tr>
            <tr>
                <th>姓名</th>
                <th>病历号</th>
                <th>性别</th>
                <th>出生年月</th>

                <th>病人基本信息-隐藏</th>
                <!--hidden fields-->

<!--
                <th>身份证号</th>
                <th>地区</th>
                <th>随访电话</th>
                <th>去世日期</th>
                <th>关系</th>
                <th>电话</th>
                <th>Email</th>
                <th>微信</th>
                <th>在随访中</th>
-->
            </tr>
        </thead>


        <tbody>
                {% for patient in patients %}
                <tr>
                    <td><a href="{{patient.get_absolute_url}}">{{patient.name}}</a></td>
                    <td><a href="{{patient.get_absolute_url}}">{{patient.EMR_id}}</a></td>
                    <td>{{patient.sex}}</td>
                    <td>{{patient.DOB}}</td>

                    <td>{{patient.sex}} | {{patient.DOB}} | {{patient.social_id}} | {{patient.location}} |{{patient.DOD}}</td>
                    <!--
                    <td>{{patient.DOB}}</td>
                    <td>{{patient.social_id}}</td>
                    <td>{{patient.location}}</td>
                    <td>{{patient.phone}}</td>
                    <td>{{patient.DOD}}</td>
                    <td>{{patient.get_relative_display}}</td>
                    <td>{{patient.relative_phone}}</td>
                    <td>{{patient.relative_email}}</td>
                    <td>{{patient.relative_wechat}}</td>
                    <td>{{patient.get_relative_in_contact_display}}</td>
                    -->
                </tr>

                {% endfor %}
        </tbody>
    </table>

                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->

{%endblock%}


{%block endscript%}
    <script src="{% static "js/jquery.dataTables.js" %}"></script>
    <link rel="stylesheet" href="{% static "css/jquery.dataTables.css" %}" />
    
    <style>
        div.dataTables_filter {
            text-align: left;
        }
        .col-sm-6 {
            width: 20%;
        }
      .filterMatches { background-color: #FFFF00; }

    </style>

    <script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    $.extend( $.fn.DataTable.defaults, {
        "searching": true,
        "ordering": true
    } );

    $(document).ready(function() {

        // //hide empty columns
        // $('#recent tr th').each(function(i) {
        //  //select all tds in this column
        //  var tds = $(this).parents('table')
        //           .find('tr td:nth-child(' + (i + 1) + ')');
        //     //check if all the cells in this column are empty
        //     if(tds.length == tds.filter(':empty').length) { 
        //         //hide header
        //         $(this).hide();
        //         //hide cells
        //         tds.hide();
        //     } 
        // });

        var table = $('#recent').DataTable( {
            //highlight search text, CHECK
            "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                var settings = this.fnSettings();
                var str = settings.oPreviousSearch.sSearch;
                var regex = new RegExp( str, 'i');
                $('td', nRow).each( function(i) {
                    this.innerHTML = aData[i].replace( regex, function(matched) { return "<span class='filterMatches'>"+matched+"</span>";});
                });
                return nRow;
            },


            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.8/i18n/Chinese.json"
            },
            //"scrollX": "100%",
            "scrollY": 450,
            "pageLength": 100,
            //"bAutoWidth": true ,
            //"fixedHeader": true,
            "order": [[ 0, "desc" ]],

            "columnDefs": [
                {"className": "dt-center","targets": "_all"},
                { "visible": false,  "targets": [ ] }
            ]


        } );

        var HIDDEN_COLUMN_INDEX = 4;

        table.on('search', function () {
            if (table.search().length) {
                table.column(HIDDEN_COLUMN_INDEX).visible(true);
            } else {
                table.column(HIDDEN_COLUMN_INDEX).visible(false);
            }
        });

        table.column(HIDDEN_COLUMN_INDEX).visible(false);

        $('#download-csv').click(function() {
            var filtered = table.rows({filter:'applied'})[0];
            $.ajax({
                method: 'POST',
                url: 'download',
                data: {
                    indexes: filtered,
                    csrfmiddlewaretoken: getCookie('csrftoken'),
                },
                success: function(response, status, xhr) {
                    // check for a filename
                    var filename = '';
                    var disposition = xhr.getResponseHeader('Content-Disposition');
                    if (disposition && disposition.indexOf('attachment') !== -1) {
                        var filenameRegex = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/;
                        var matches = filenameRegex.exec(disposition);
                        if (matches != null && matches[1]) filename = matches[1].replace(/['"]/g, '');
                    }

                    var type = xhr.getResponseHeader('Content-Type');
                    var blob = new Blob([response], { type: type });

                    if (typeof window.navigator.msSaveBlob !== 'undefined') {
                        // IE workaround for "HTML7007: One or more blob URLs were revoked by closing the blob for which they were created. These URLs will no longer resolve as the data backing the URL has been freed."
                        window.navigator.msSaveBlob(blob, filename);
                    } else {
                        var URL = window.URL || window.webkitURL;
                        var downloadUrl = URL.createObjectURL(blob);

                        if (filename) {
                            // use HTML5 a[download] attribute to specify filename
                            var a = document.createElement("a");
                            // safari doesn't support this yet
                            if (typeof a.download === 'undefined') {
                                window.location = downloadUrl;
                            } else {
                                a.href = downloadUrl;
                                a.download = filename;
                                document.body.appendChild(a);
                                a.click();
                            }
                        } else {
                            window.location = downloadUrl;
                        }

                        setTimeout(function () { URL.revokeObjectURL(downloadUrl); }, 100); // cleanup
                    }
                }
            });
        });

    } ); //table end
    </script>
{%endblock%}

cancer/dashboard/templates/consoleView/userConsole.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
{% load staticfiles %}
{% block script %}

<script src="{% static "js/jquery.dataTables.js" %}"></script>
<link rel="stylesheet" href="{% static "css/jquery.dataTables.css" %}" />


{% endblock%}


{% block content %}


        <div class="blogsHero" style="background-image:url({% static "images/blog-bg.jpg" %});">
           <div class="small-12 columns tableCell">
              <div class="text-center labHeroText cell">
                <h1>Welcome {{user.username}}!</h1>
                <h3></h3>
              </div>
            </div>
         </div>


<ul class="breadcrumb">
  <li><a href="/">Home</a></li>
  <li><a href="/virtual">Planned MiSeq</a></li>
  <li class="active">User Console</li>
</ul>
       

<div>
        <div class="small-12 columns">
             <div class="small-12 medium-4 columns blog_inspire">
               <a href="/virtual/console/log/">
                 <div class="blog_mainImage" style="background-image:url({% static "images/textures/1.jpg"%});"><h2>Add new Log</h2></div>
               </a>
               <div class="blogs_description">
                 <h5></h5>
    
                 <a href="/virtual/console/log/" class="blog_viewAll" style="background:#808080;">Logging Center</a>
               </div>
             </div>
            
             <div class="small-12 medium-4 columns blog_inspire">
               <a href="/virtual/console/#experiments">
                 <div class="blog_mainImage" style="background-image:url({% static "images/textures/2.jpg"%});"><h2>My Experiments</h2></div>
               </a>
               <div class="blogs_description">
                 <h5></h5>

                 <a href="/virtual/console/myexperiments/" class="blog_viewAll" style="background:#808080;">Experiment Management Center</a>
               </div>
             </div>
             

             <div class="small-12 medium-4 columns blog_inspire">

               <a href="/virtual/console/account/#setting">
                 <div class="blog_mainImage" style="background-image:url({% static "images/textures/3.jpg"%});"><h2>Account Settings</h2></div>
               </a>
               <div class="blogs_description">
                 <h5></h5>

                 <a href="/virtual/console/account/" class="blog_viewAll" style="background:#808080;">Account Center</a>
               </div>
             </div>
           

         </div>
</div>


<div  style="width: 100%;margin-left:auto;margin-right:auto;text-align:center;">
<hr>
<div class="jumbotron" id='experiments'>
  <h2 align='middle'>My Experiments:</h2>
<hr>

{%include "exp_table.html"%}

</div>
<hr>



{% endblock %}

</body></html>